### ISSUE TITLE
Speed test for 64 bit generators uses wrong function

### ISSUE THREAD

**Issue by zokier** [lemire/testingRNG#1]
I think there might be a problem here:

https://github.com/lemire/testingRNG/blob/b608ed362d10758ede5d357fb53e737e38b9d322/speed/src/rng.c#L107

It probably should be calling `populate64` instead. Now unless I'm mistaken only half of the buffer gets filled.

**Comment by lemire** [comment]
Yep Great work! https://github.com/lemire/testingRNG/commit/c88bc9dbc8dac0a0e7a14ee57fee58a487e36527

**Comment by lemire** [comment]
Bug did not seem to affect timings. Bits were just discarded.
