### ISSUE TITLE
(Issue withdrawn)

### ISSUE THREAD

**Issue by peteroupc** [lemire/testingRNG#10]
(Issue withdrawn)

**Comment by lemire** [comment]
The issue, which you withdrew, was...

> For 64-bit generators, did you consider converting each 64-bit value (and/or its byte reversed and/or bit reversed version) into floating-point numbers for TestU01, in addition to the other tests it performs? Note that TestU01 offers a unif01_CreateExternGen01 method for this purpose.

This seemed reasonable enough. No, it was not considered.

**Comment by peteroupc** [comment]
Thank you for commenting.  I am not forcing you or requesting you to consider my issue, since it's now withdrawn.

**Comment by lemire** [comment]
Do you mind if I reopen it? It seems sensible.

**Comment by peteroupc** [comment]
I'm so sorry, but this suggestion was truly made by mistake.  Please act as though I never posted this issue.  I would have deleted it (as I could on other forums), but GitHub offers no way to do so.

**Comment by lemire** [comment]
Ok.
