### ISSUE TITLE
What should be the input to the statistical tests?

### ISSUE THREAD

**Issue by famunir** [lemire/testingRNG#11]
Hello. I have been trying to perform testU01. I am unable to understand what should be the input to tests? I performed NIST tests and all I have to provide NIST tests is a random sequence in a text file generated by my RNG. Does testu01 works the same? or do I have to provide the whole code of my RNG to testu01 suite and it will generate the sequence itself and then test it. There is almost no help or very little help regarding the usage of testu01 online. I would appreciate any kind of help. Thank you!

**Comment by lemire** [comment]
TestU01 comes with extensive documentation, down to a detailed description of the algorithms. Please look again.
