### ISSUE TITLE
wyhash/rng

### ISSUE THREAD

**Issue by wangyi-fudan** [lemire/testingRNG#12]
Dear Lemire:
I am a fan of you :-)
Recently I developed a new fastest hash function wyhash, which is recognized by SMHasher. Based on it, I developed a new PRNG which is the fastest based on your benchmark, and passes practrand and BigCrush (those there is a p-value of 2e-4 which is common if we consider multiple testing).  It is located at https://github.com/wangyi-fudan/wyhash

**Comment by lemire** [comment]
My version of your generator...
https://github.com/lemire/testingRNG/blob/master/source/wyhash.h

I confirm your good speed results. On x64, I expect that you will have superb speed.

On ARM, you are going to suffer, however.

**Comment by lemire** [comment]
Closing.

**Comment by lemire** [comment]
If you beat lehmer64 then I suggest something is wrong with your benchmark. It is likely unbeatable (a single multiplication) on x64,
