### ISSUE TITLE
wyrng: missing inline

### ISSUE THREAD

**Issue by wangyi-fudan** [lemire/testingRNG#13]
Dear Lemire:
 In your wyrng simplification code, you missed a inline keyword which make wyrng slower. 

inline	uint64_t wyhash64_stateless(uint64_t *seed) {

adding this inline, wyrng is the fastest :-)

**Comment by lemire** [comment]
> you missed a inline keyword which make wyrng slower.

Have you checked the assembly? With all compilers I can try on my test machine, the function gets inlined as it is obviously desirable.

**Comment by lemire** [comment]
Added the inline keyword. No change either to the binary or to the performance.
