### ISSUE TITLE
summarize.pl not found

### ISSUE THREAD

**Issue by jherekhealy** [lemire/testingRNG#21]
Thanks for this nice rng test suite.
I could not find summarize.pl file however. What does it do? how is a blip defined?

**Comment by jherekhealy** [comment]
Ah I found it in results, for some reasons, github did not show it by a search.
I suppose a blip is for the results verifying 1e-3 > p-value > 1e-10. Would be nice to see some stats on the blips (lowest p-value blip for example)

**Comment by lemire** [comment]
The file is not part of the code of our repository.

> I suppose a blip is for the results verifying 1e-3 > p-value > 1e-10. Would be nice to see some stats on the blips (lowest p-value blip for example)

It all belongs to the `testu01` package which we use but do not modify. Please refer to the documentation of the `testu01` package
