### ISSUE TITLE
aesctr templating

### ISSUE THREAD

**Issue by dnbaker** [lemire/testingRNG#5]
I've used your AES-CTR implementation in a couple of projects. Over time, I've made a few changes. It's compatible with boost/C++11 <random>, and templated over all integral types and by UNROLL_COUNT.

On my machines, an UNROLL_COUNT of 8 (rather than 4) was measurably but not enormously faster. (~10% speed increase.)

I don't want to assume you want it included, but I'm mentioning it just in case. Here's a link to the [current version I use](https://github.com/dnbaker/hll/blob/master/aesctr.h).

**Comment by lemire** [comment]
I have added a link to your version. Please see...

https://github.com/lemire/testingRNG/blob/master/source/aesctr.h#L2-L5
