### ISSUE TITLE
possible typo

### ISSUE THREAD

**Issue by lemire** [lemire/testingRNG#8]
Should be a plus...

https://github.com/lemire/testingRNG/blob/8f205bf63f21475739d408271b1bc0f1d3efae27/source/splitmix64.h

**Comment by bduvenhage** [comment]
I didn't notice that you added this issue. I created a pull request https://github.com/lemire/testingRNG/pull/9 for the same.

**Comment by lemire** [comment]
I created this issue following your comment... I like to leave a trace.

Let us close this issue.
